### PR TITLE
Update complete.txt

### PR DESCRIPTION
**Pull request by ejeancolas**
Some more factorisations: c162, c175, c176, c177, c189, c198 and c201

### CODE REVIEW

**Comment by 007** [comment]
Wow, thanks!

I'll verify these shortly and get them merged.

**Comment by 007** [comment]
LGTM, will add certificates and other peripheral stuff in a few minutes.

**Comment by ejeancolas** [comment]
Hello

Glad to see this list is active.

My plan is to get all the 200 first numbers factored, using ecm and/or cado-nfs, and then make a scan to the composite numbers up to 1000 digits with a ecm 11e6.
Well, it will take a while. As I have other jobs ongoing, I think I will be able to get the 4 remaining numbers not before end of summer, and send updates on newly factorized numbers between 200 and 1000 digits by end of year.

Note: 31415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679821480865132823066470938446095505822317253594081284811174502841027019385211055596446229489 = 3 ^ 2 * 37 * 73 * 16963 * 281862535884901 * 1755888679270787 * 768220096897658236065493556092750699123 * 20507597512393249624309456735559147923624280315177833 * 9771142201615011864166663027210919919094528987091935625826499
(factorized this morning)
I don't know if it is better just to send you this information, or go thru the pull/merge process.

Best regards

**Comment by 007** [comment]
It's up to you if you'd like to do PRs or if you want to send what you have through and I can add it in. I'll take any help I can get.

You can open an issue instead of a PR if you want, then you can paste in whatever you find and I'll reformat and generate certificates and all.

If you're using gmp-ecm from INRIA then please keep note of your B1, B2 and sigma in sigmalog.txt. These factors are going to be some of the largest to be found just through brute force, and you may be setting a record without even realizing!

**Comment by ejeancolas** [comment]
Hello,

About how I factorize, I do first an ecm run, and whenever I find a composite factor of less than 150 digits, I run cado-nfs to finish factorizations. That how I have been able to send you an update and to do PR updates.
I'll make an exception about the four missing on the first 200 numbers generated from pi. About c193, there is a c151 not too difficult for cado-nfs. I will factorize it on June if not factorized before. About c199, there is a c161. This is a 15-day run on my computer. Well, maybe in July. About c180 and c185, there are c166's. It will take months for cado-nfs. But it is temptating to finish the job...
I am running a ecm 11e6 on the remaining composite factors as well. But as you know, it is long! Whenever I'll find a factor, I will update sigmalog as well.
I submit here (the easiest way for me) some more factorized numbers, factorized with cado-nfs.

c216
314159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534211706798214808651328230664709384460955058223172535940812848111745028410270193852110555964462294895493038196442881097566593 = 47 * 27582284664523 * 100192070117707 * 3111840291443309 * 251947480406003949481360216346086567530587 * 124531685639982052581994853042381105643950989951337 * 24773150592729073015910846293590433935987049853873607105267414246575780875261649

c224
31415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679821480865132823066470938446095505822317253594081284811174502841027019385211055596446229489549303819644288109756659334461284 = 2 ^ 2 * 223 * 431 * 177421 * 861979 * 49984124958080227 * 4058236198340011857045956418353858770783 * 47193439481807353102194503186619241843003 * 23818558774841458349963162808806460538139705621 * 2343362719914641815395961291540372184541877370360756504135028661

c231
314159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534211706798214808651328230664709384460955058223172535940812848111745028410270193852110555964462294895493038196442881097566593344612847564823 = 3 * 6125947 * 170143147 * 300773256739 * 7176797356030663837193688482587 * 150738292651719770573995690985150856738877 * 6687270123867656060579947651079942823398386341718806292389793 * 46174112986634968744877736915463894729246773417685377223940133131214313

Best regards.

----- Mail original -----
De: "Ryan Moore" <notifications@github.com>
À: "007/primemath" <primemath@noreply.github.com>
Cc: "ejeancolas" <eric.jeancolas@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Lundi 29 Avril 2019 16:44:12
Objet: Re: [007/primemath] Update complete.txt (#1)



It's up to you if you'd like to do PRs or if you want to send what you have through and I can add it in. I'll take any help I can get. 

You can open an issue instead of a PR if you want, then you can paste in whatever you find and I'll reformat and generate certificates and all. 

If you're using gmp-ecm from INRIA then please keep note of your B1, B2 and sigma in sigmalog.txt. These factors are going to be some of the largest to be found just through brute force, and you may be setting a record without even realizing!

**Comment by ejeancolas** [comment]
Hello Ryan
I issued two PR a week ago on 007/primemath
This note just to check the process is ok.
Cheers


----- Mail original -----
De: "Ryan Moore" <notifications@github.com>
À: "007/primemath" <primemath@noreply.github.com>
Cc: "ejeancolas" <eric.jeancolas@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Lundi 29 Avril 2019 16:44:12
Objet: Re: [007/primemath] Update complete.txt (#1)



It's up to you if you'd like to do PRs or if you want to send what you have through and I can add it in. I'll take any help I can get. 

You can open an issue instead of a PR if you want, then you can paste in whatever you find and I'll reformat and generate certificates and all. 

If you're using gmp-ecm from INRIA then please keep note of your B1, B2 and sigma in sigmalog.txt. These factors are going to be some of the largest to be found just through brute force, and you may be setting a record without even realizing!

**Comment by ejeancolas** [comment]
Hi Ryan

I eventualy achieved the 3 missing factorization to get a the full factorization table of pi numbers up to 200 digits. This was a bit long to achieve, you'll see that these numbers contain large factors.
Note that I updated factordb.com as well.
Here are the numbers :

314159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534211706798214808651328230664709384460955058223172535940812848111745028410270193852110555 = 3^4*5*13*241*60209671*6166204699465324316051997602974133365825682868692202965894080422554737086691*666883945792363639678274125621027155072642129068012309239350028746627170413376060310193487

31415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679821480865132823066470938446095505822317253594081284811174502841027019385211055596446 = 2*599*24902402522691619*73394616727171464984332074817757705638720304246806734910998259700383*14347875480732542359912576705050811049151946741150502349716440708684906316609059114899596915672701

3141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825342117067982148086513282306647093844609550582231725359408128481117450284102701938521105559644622948954930381 = 3*1095000521*81143882621*426565741419741731*673645067087480721151694045217838307811752578521276767191381263647*41014875800874399747559895414934134097183184026394479945372490926453297972357097089204975137471

I didn't enter PR. I let you update the lists (worktodo/pi.txt, pi_fact.txt, complete.txt).

My aim is still to factor any number I find on web projects with less than 200 digits. About pi, this is now over.

Thank you for having put this project on github.

Best regards.

Eric

**Pull request merged**
